repos:
  - repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
      - id: black
        language_version: python3.9
        additional_dependencies: [ regex == 2021.9.30 ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "mypy"
        language: python
        language_version: python3.9
        types: [python]
        require_serial: true
        verbose: true
        additional_dependencies: [types-all]